const express = require("express")
const cors = require("cors")
const helmet = require("helmet")
const morgan = require("morgan")
const app = express()
app.use(helmet())
app.use(cors({ origin: process.env.CLIENT_URL || "http://localhost:5173" }))
app.use(express.json())
app.use(morgan("dev"))
app.get("/api/health", (_req, res) => res.status(200).json({ status: "ok", service: "EduSuccess API" }))
app.use((_req, res) => res.status(404).json({ message: "Route not found" }))
module.exports = app
